# Site settings
name: Alina
email: lindenalina.al@gmail.com
url: https://slothql.github.io/blog/
description: "A blog and a portfolio"
author: "Alina"
title: "Blog"
permalink: pretty
baseurl:

# social
github:
  username: SlothQL

twitter:
  username: SlothQL
