# Site settings
name: SlothQL
email: lindenalina.al@gmail.com
url: https://slothql.dev
description: "A blog and a portfolio"
author: "Alina"
title: "Blog"
permalink: pretty
baseurl:

# social
github:
  username: SlothQL

twitter:
  username: SlothQL
