# Site settings
name: Alina
email: lindenalina.al@gmail.com
url: url
description: "A blog and a portfolio"
author: "author"
title: "BlogFolio"
permalink: pretty
baseurl:

# social
github:
  username: SlothQL

twitter:
  username: @SlothQL
